apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: airflow-db
  namespace: {{ .Values.namespace }}
spec:
  serviceName: "airflow-db"
  replicas: 1
  selector:
    matchLabels:
      app: airflow-db
  template:
    metadata:
      labels:
        app: airflow-db
    spec:
      containers:
      - name: postgres
        image: {{ .Values.postgresql.image }}:{{ .Values.postgresql.tag }}
        envFrom:
        - secretRef:
            name: {{ .Values.postgresql.secretName }}
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-db
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 5432
  selector:
    app: airflow-db