apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: airflow-db
spec:
  serviceName: "airflow-db"
  replicas: 1
  selector:
    matchLabels:
      app: airflow-db
  template:
    metadata:
      labels:
        app: airflow-db
    spec:
      containers:
      - name: postgres
        image: bitnami/postgresql:latest 
        env:
        - name: POSTGRES_PASSWORD
          value: "airflow"
        - name: POSTGRES_DB
          value: "airflow"
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-db
spec:
  ports:
    - port: 5432
  selector:
    app: airflow-db