apiVersion: v2
name: airflow
description: Apache Airflow - A platform to programmatically author, schedule, and monitor workflows
type: application
version: 0.1.0
appVersion: "2.8.1"

dependencies:
  - name: airflow
    version: "1.13.1"
    repository: https://airflow.apache.org
