apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dagster
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/woohyeonDev/gitOpsInfra.git
    targetRevision: main
    path: apps/dagster
    helm:
      chart: dagster/dagster
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: dagster

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
